home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('status', views.StatusView.as_view(), name='status'),
    path('', views.TopView.as_view(), name='top'),
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'
urlpatterns = [
    path('create/', views.ReviewCreateView.as_view(), name='create'),
    path('list/', views.ReviewListView.as_view(), name='list'),
]

shops/urls.py
from django.urls import path

from . import views

app_name = 'shops'
urlpatterns = [
    path('ranking/', views.ShopRankingView.as_view(), name='ranking'),
    path('create/', views.ShopCreateView.as_view(), name='create'),
]

tabetalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('shops/', include('shops.urls')),
    path('reviews/', include('reviews.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from shops.models import Shop

UserModel = get_user_model()


class Review(models.Model):
    """
    口コミ情報を表すモデル
    各フィールドは reviews_review テーブルのカラムにマッピングされる
    """
    # コメント
    comment = models.CharField(max_length=1000)
    # 画像
    photo = models.ImageField(blank=True, null=True)
    # 評価点数
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    # ショップ（Shop モデルへの外部参照）
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    # 投稿者（ユーザーモデルへの外部参照）
    posted_by = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    # 投稿日時
    posted_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def list_latest(cls):
        return cls.objects.order_by('posted_at').reverse()

    def has_score(self):
        return self.score is not None

shops/models.py
import logging

from django.db import models

log = logging.getLogger(__name__)


class Prefecture(models.Model):
    name = models.CharField(max_length=3)

    def __str__(self):
        return self.name


class Budget(models.Model):
    lowest = models.IntegerField()
    highest = models.IntegerField()


class Shop(models.Model):
    name = models.CharField(max_length=128)
    kana_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=10)
    prefecture = models.ForeignKey(Prefecture, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)

    @classmethod
    def list_all(cls):
        return cls.objects.all()

    @classmethod
    def list_ranking(cls, head=None):
        return sorted(
            cls.objects.all().prefetch_related('review_set'),
            key=lambda x: x.score, reverse=True
        )[0:head]

    @property
    def score(self):
        scores = [r.score for r in self.review_set.all() if r.score]
        return sum(scores) / len(scores) if scores else 0

    def __str__(self):
        return self.name


class ShopProfile(models.Model):
    shop = models.OneToOneField(Shop, on_delete=models.CASCADE)
    access = models.CharField(max_length=255)
    business_hours = models.CharField(max_length=255)
    regular_holiday = models.CharField(max_length=255)
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    url = models.URLField()

home/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView, View

from reviews.models import Review
from shops.models import Shop


class TopView(TemplateView):
    template_name = 'home/top.html'

    def get_context_data(self, **kwargs):
        kwargs['shop_list'] = Shop.list_ranking(head=3)
        kwargs['review_list'] = Review.list_latest()[:10]
        return super().get_context_data(**kwargs)


class StatusView(View):

    def get(self, request):
        return HttpResponse('動画投稿アプリは正常に起動しています。')

home/templates/home/top.html
{% extends "../base.html" %}
{% load static %}

{% block title %}トップ{% endblock %}

{% block content %}
<section class="content">
  <div class="row">
    <div class="col-sm"><h2><span>人気のお店TOP3</span></h2></div>
    <div class="col-sm text-right"><a href="{% url "shops:create" %}" class="btn btn-secondary">新しいお店を登録する</a></div>
  </div>
  <ol>
    {% for shop in shop_list %}
    <li>
      {% include "shops/cassette.html" %}
    </li>
    {% endfor %}
  </ol>
  <p class="text-right"><a href="{% url "shops:ranking" %}">もっと見る</a></p>
</section>
<section class="content">
  <div class="row">
    <div class="col-sm"><h2><span>新着口コミ</span></h2></div>
    <div class="col-sm text-right"><a href="{% url "reviews:create" %}" class="btn btn-secondary">口コミを投稿する</a></div>
  </div>
  <ul>
    {% for review in review_list %}
    <li>
      {% include "reviews/cassette.html" %}
    </li>
    {% endfor %}
  </ul>
  <p class="text-right"><a href="{% url "reviews:list" %}">もっと見る</a></p>
</section>
{% endblock %}

{% block footer_js %}
  {% include "../js/rating.html" %}
{% endblock %}